export const auth = {
    token : "Bearer BQAfwkkabaLamIwpSLv2IR3OxRKBVI-31u5lJb2y1HBxYtOjUc5ci5vaPJylLFGNMFpqN4IYdUIytkzLRS-uAuDqLeBsUflEwvefce-3ktn1lWaYaLY2wBWYrU5RBbDgw9uSK2XO3DiUhXOhH_-7RigWvQGSUXMTPZrH3Gre2SOXneO_Ogfd3aQxlluHYLaHQnlQBzNwet0a4VauOKeLHo0"
}